# Form implementation generated from reading ui file 'ReDesignedMAIMAI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.setEnabled(True)
        Main.resize(400, 300)
        Main.setMinimumSize(QtCore.QSize(400, 300))
        self.gridLayout = QtWidgets.QGridLayout(Main)
        self.gridLayout.setObjectName("gridLayout")
        self.Welcome = QtWidgets.QLabel(parent=Main)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.Welcome.setFont(font)
        self.Welcome.setTabletTracking(False)
        self.Welcome.setObjectName("Welcome")
        self.gridLayout.addWidget(self.Welcome, 0, 0, 1, 1)
        self.ButtonLogin = QtWidgets.QPushButton(parent=Main)
        self.ButtonLogin.setIconSize(QtCore.QSize(32, 32))
        self.ButtonLogin.setObjectName("ButtonLogin")
        self.gridLayout.addWidget(self.ButtonLogin, 1, 0, 1, 1)
        self.ButtonSignup = QtWidgets.QPushButton(parent=Main)
        self.ButtonSignup.setObjectName("ButtonSignup")
        self.gridLayout.addWidget(self.ButtonSignup, 2, 0, 1, 1)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "ReDesignedMAIMAI"))
        Main.setWhatsThis(_translate("Main", "<html><head/><body><p>重构式音游手台</p></body></html>"))
        self.Welcome.setText(_translate("Main", "<html><head/><body><p align=\"center\">欢迎使用本软件</p></body></html>"))
        self.ButtonLogin.setText(_translate("Main", "登录"))
        self.ButtonSignup.setText(_translate("Main", "注册"))
