# Form implementation generated from reading ui file '人脸进入UI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FaceIdentify(object):
    def setupUi(self, FaceIdentify):
        FaceIdentify.setObjectName("FaceIdentify")
        FaceIdentify.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(FaceIdentify)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Identify = QtWidgets.QLabel(parent=FaceIdentify)
        self.Identify.setObjectName("Identify")
        self.verticalLayout.addWidget(self.Identify)
        self.Notice = QtWidgets.QLabel(parent=FaceIdentify)
        self.Notice.setObjectName("Notice")
        self.verticalLayout.addWidget(self.Notice)
        self.Next = QtWidgets.QPushButton(parent=FaceIdentify)
        self.Next.setObjectName("Next")
        self.verticalLayout.addWidget(self.Next)

        self.retranslateUi(FaceIdentify)
        QtCore.QMetaObject.connectSlotsByName(FaceIdentify)

    def retranslateUi(self, FaceIdentify):
        _translate = QtCore.QCoreApplication.translate
        FaceIdentify.setWindowTitle(_translate("FaceIdentify", "人脸识别"))
        self.Identify.setText(_translate("FaceIdentify", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:700;\">人脸识别系统</span></p></body></html>"))
        self.Notice.setText(_translate("FaceIdentify", "<html><head/><body><p><span style=\" font-size:12pt;\">注意事项：</span></p></body></html>"))
        self.Next.setText(_translate("FaceIdentify", "继续"))
