# Form implementation generated from reading ui file '人脸导引.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FaceGuide(object):
    def setupUi(self, FaceGuide):
        FaceGuide.setObjectName("FaceGuide")
        FaceGuide.resize(482, 252)
        self.gridLayout = QtWidgets.QGridLayout(FaceGuide)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=FaceGuide)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=FaceGuide)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(FaceGuide)
        QtCore.QMetaObject.connectSlotsByName(FaceGuide)

    def retranslateUi(self, FaceGuide):
        _translate = QtCore.QCoreApplication.translate
        FaceGuide.setWindowTitle(_translate("FaceGuide", "Face Guide"))
        self.label.setText(_translate("FaceGuide", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:700;\">您已成功注册！是否录入人脸数据？</span></p></body></html>"))
