# Form implementation generated from reading ui file '模式选择.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ModeSelection(object):
    def setupUi(self, ModeSelection):
        ModeSelection.setObjectName("ModeSelection")
        ModeSelection.resize(384, 240)
        self.gridLayout = QtWidgets.QGridLayout(ModeSelection)
        self.gridLayout.setObjectName("gridLayout")
        self.Modes = QtWidgets.QComboBox(parent=ModeSelection)
        self.Modes.setEditable(False)
        self.Modes.setCurrentText("")
        self.Modes.setDuplicatesEnabled(False)
        self.Modes.setModelColumn(8)
        self.Modes.setObjectName("Modes")
        self.gridLayout.addWidget(self.Modes, 0, 0, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ModeSelection)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 2)
        self.RecommendedMode = QtWidgets.QLabel(parent=ModeSelection)
        self.RecommendedMode.setObjectName("RecommendedMode")
        self.gridLayout.addWidget(self.RecommendedMode, 2, 1, 1, 1)
        self.Recommend = QtWidgets.QLabel(parent=ModeSelection)
        self.Recommend.setObjectName("Recommend")
        self.gridLayout.addWidget(self.Recommend, 2, 0, 1, 1)

        self.retranslateUi(ModeSelection)
        QtCore.QMetaObject.connectSlotsByName(ModeSelection)

    def retranslateUi(self, ModeSelection):
        _translate = QtCore.QCoreApplication.translate
        ModeSelection.setWindowTitle(_translate("ModeSelection", "模式选择"))
        self.Modes.setPlaceholderText(_translate("ModeSelection", "请选择模式"))
        self.RecommendedMode.setText(_translate("ModeSelection", "SomeMode"))
        self.Recommend.setText(_translate("ModeSelection", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:700;\">推荐模式：</span></p></body></html>"))
