# Form implementation generated from reading ui file '注册.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SignUp(object):
    def setupUi(self, SignUp):
        SignUp.setObjectName("SignUp")
        SignUp.resize(403, 320)
        self.layoutWidget = QtWidgets.QWidget(parent=SignUp)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 361, 221))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Username = QtWidgets.QLabel(parent=self.layoutWidget)
        self.Username.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Username.setWordWrap(False)
        self.Username.setOpenExternalLinks(False)
        self.Username.setObjectName("Username")
        self.verticalLayout.addWidget(self.Username, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.Username_SignUp = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.Username_SignUp.setText("")
        self.Username_SignUp.setObjectName("Username_SignUp")
        self.verticalLayout.addWidget(self.Username_SignUp)
        self.Password = QtWidgets.QLabel(parent=self.layoutWidget)
        self.Password.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Password.setObjectName("Password")
        self.verticalLayout.addWidget(self.Password)
        self.Password_SignUp = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.Password_SignUp.setObjectName("Password_SignUp")
        self.verticalLayout.addWidget(self.Password_SignUp)
        self.Password_Forsure = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.Password_Forsure.setObjectName("Password_Forsure")
        self.verticalLayout.addWidget(self.Password_Forsure)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.layoutWidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SignUp)
        QtCore.QMetaObject.connectSlotsByName(SignUp)

    def retranslateUi(self, SignUp):
        _translate = QtCore.QCoreApplication.translate
        SignUp.setWindowTitle(_translate("SignUp", "Sign Up"))
        self.Username.setText(_translate("SignUp", "<html><head/><body><p><span style=\" font-size:18pt;\">用户名</span></p></body></html>"))
        self.Username_SignUp.setPlaceholderText(_translate("SignUp", "请输入用户名"))
        self.Password.setText(_translate("SignUp", "<html><head/><body><p><span style=\" font-size:18pt;\">密码</span></p></body></html>"))
        self.Password_SignUp.setPlaceholderText(_translate("SignUp", "请输入密码"))
        self.Password_Forsure.setPlaceholderText(_translate("SignUp", "请确认密码"))
